apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfect-api
  labels:
    driveby.io/version: "2.0.0"
    app: perfect-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perfect-api
  template:
    metadata:
      labels:
        driveby.io/version: "2.0.0"
        app: perfect-api
    spec:
      containers:
        - name: api
          image: ghcr.io/novelcore/perfect-api:1dd5303c7345bb980503cae04746d01d995565f9
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              value: "driveby-test-key-2024"
          livenessProbe:
            httpGet:
              path: /test/health
              port: 8000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /test/health
              port: 8000
            initialDelaySeconds: 3
      imagePullSecrets:
        - name: ghcr-creds
